apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertingrules.monitoring.openshift.io
spec:
  group: monitoring.openshift.io
  version: v1alpha1
  names:
    kind: AlertingRule
    listKind: AlertingRuleList
    singular: alertingrule
    plural: alertingrules
  scope: Namespaced
