apiVersion: monitoring.openshift.io/v1alpha1
kind: HealingRule
metadata:
  name: node-down
spec:
  conditions:
  - alert: node-down-0
  actions:
  - awxJob:
      address: https://tower.private/api
      secretRef:
        name: awx
      project: "Healing actions"
      template: "Ensure nodes"
